name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v -o ./cmd/accessbot/accessbot ./cmd/accessbot/main.go
      - name: execut
        run: ./cmd/accessbot/accessbot
