name: Deploy
on:
  release:
    types: [published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build -v -o ./cmd/accessbot/accessbot ./cmd/accessbot/main.go
      - name: setup-qemu
        uses: docker/setup-qemu-action@v2
      - name: setup-docker-buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: inclunet/accessbot
      - name: What
        run: pwd & ls -la & cd cmd && ls && cd accessbot & ls
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
